version: '3.9'

services:
  db:
    image: postgres:latest
    container_name: tekove_postgres
    environment:
      POSTGRES_USER: tekove
      POSTGRES_PASSWORD: tekove123
      POSTGRES_DB: tekove
    volumes:
      - dados_db:/var/lib/postgresql/data
      - ./sqls/:/docker-entrypoint-initdb.d/
    ports:
      - "5432:5432"
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  web:
    build: ./app
    container_name: tekove_flask
    environment:
      FLASK_APP: app.py
      FLASK_ENV: development
      DATABASE_URL: postgres://tekove:tekove123@db:5432/tekove
    ports:
      - "5000:5000"
    depends_on:
      - db

volumes:
  dados_db:
